name: GitHub Actions Demo
on: 
  push:
    branches: 
    - main
    paths-ignore: 
    - '.github/**'
  pull_request:
    branches: 
    - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
        environment:
          description: 'Environment to deploy to'
          type: environment
          required: true
jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."      
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - run: tree

  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    steps:
      - run: echo "🧪 Testing..."
              sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run:
          for var in 1 2 3 4 5
            do echo "🚀 Step ${{var}}..."
            sleep 10
          done
